name: Lead Generation and Sales

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub
  schedule:
    - cron: "0 10 * * *"  # Corre todos los días a las 10 AM UTC

jobs:
  capturar_leads:
    name: Captura de Leads
    runs-on: ubuntu-latest

    steps:
      - name: Configurar entorno
        run: echo "🔧 Preparando entorno para capturar leads..."

      - name: Capturar Leads desde Webhook
        run: |
          echo "📡 Enviando datos a Webhook.site..."
          curl -X POST https://webhook.site/b5e9f919-3748-4024-8c46-d472e28930f7 \
               -H "Content-Type: application/json" \
               -d '{
                     "evento": "nueva_inversion",
                     "cliente_id": "MELANO123",
                     "monto": 5000,
                     "token": "USDT",
                     "bot": "scalping"
                   }'

      - name: Guardar Leads en Google Sheets
        run: |
          echo "📊 Guardando lead en Google Sheets..."
          curl -X POST "https://script.google.com/macros/s/AKfycbyVsqcnJ1T7DHkBIwff3_Vdw88hBwFo-o7Z-87hH8dSO2GpYYhQL7_ANCIhnc_PEEEX/exec" \
               -H "Content-Type: application/json" \
               -d '{"cliente_id": "MELANO123", "monto": 5000, "token": "USDT"}'

      - name: Enviar WhatsApp a Lead
        run: |
          echo "📲 Enviando WhatsApp al lead..."
          curl -X POST "https://api.nueva-whatsapp.com/send" \
               -H "Content-Type: application/json" \
               -d '{"telefono": "+5491122334455", "mensaje": "Gracias por contactarnos, tu inversión ya está en proceso 🚀"}'


  seguimiento_automatico:
    name: Seguimiento Automático
    runs-on: ubuntu-latest

    steps:
      - name: Detectar Leads sin Respuesta
        run: |
          # Detectar leads sin seguimiento en el CRM
          echo "Buscando leads sin respuesta..."

      - name: Enviar Recordatorio por WhatsApp/Email
        run: |
          # Enviar recordatorio al lead
          echo "Enviando recordatorio por WhatsApp"

      - name: Actualizar Estado en CRM
        run: |
          # API para actualizar el estado del lead en el CRM
          echo "Marcando lead como 'En seguimiento'"

  alerta_lead_caliente:
    name: Alerta por Lead Caliente
    runs-on: ubuntu-latest

    steps:
      - name: Detectar Actividad en Emails
        run: |
          # Analiza actividad en correos
          echo "Detectando actividad reciente en emails..."

      - name: Crear Tarea en CRM
        run: |
          # Crear alerta interna y asignar tarea a responsable
          echo "Creando tarea en CRM para lead caliente"
