name: Lead Generation and Sales

on:
  workflow_dispatch:  # Ejecución manual
  schedule:
    - cron: "0 10 * * *"  # Todos los días a las 10 AM UTC

jobs:
  capturar_leads:
    name: Captura de Leads
    runs-on: ubuntu-latest

    steps:
      - name: Configurar entorno
        run: echo "🔧 Preparando entorno para capturar leads..."

      - name: Capturar Leads desde Webhook
        run: |
          echo "📡 Enviando datos a Webhook.site..."
          curl -X POST https://webhook.site/b5e9f919-3748-4024-8c46-d472e28930f7 \
               -H "Content-Type: application/json" \
               -d '{
                     "evento": "nueva_inversion",
                     "cliente_id": "MELANO123",
                     "monto": 5000,
                     "token": "USDT",
                     "bot": "scalping"
                   }'

      - name: Guardar Leads en Google Sheets
        run: |
          echo "📊 Guardando lead en Google Sheets..."
          curl -X POST "https://script.google.com/macros/s/AKfycbyVsqcnJ1T7DHkBIwff3_Vdw88hBwFo-o7Z-87hH8dSO2GpYYhQL7_ANCIhnc_PEEEX/exec" \
               -H "Content-Type: application/json" \
               -d '{"cliente_id": "MELANO123", "monto": 5000, "token": "USDT"}'

      - name: Enviar WhatsApp a Lead (TEST con UltraMsg)
        run: |
          echo "🧪 Enviando WhatsApp de prueba..."
          curl -X POST "https://api.ultramsg.com/${{ secrets.INSTANCE_ID }}/messages/chat" \
               -H "Content-Type: application/x-www-form-urlencoded" \
               -d "token=${{ secrets.ULTRA_TOKEN }}" \
               -d "to=+5492235506585" \
               -d "body=🚀 Gracias por contactarte con MELANO INC. Tu inversión está en proceso."

  seguimiento_automatico:
    name: Seguimiento Automático
    runs-on: ubuntu-latest

    steps:
      - name: Detectar Leads sin Respuesta
        run: |
          echo "🔍 Buscando leads sin respuesta en CRM..."

      - name: Enviar Recordatorio por WhatsApp/Email
        run: |
          echo "📲 Enviando recordatorio por WhatsApp..."

      - name: Actualizar Estado en CRM
        run: |
          echo "✅ Marcando lead como 'En seguimiento' en CRM..."

  alerta_lead_caliente:
    name: Alerta por Lead Caliente
    runs-on: ubuntu-latest

    steps:
      - name: Detectar Actividad en Emails
        run: |
          echo "🔥 Detectando apertura/click en campañas..."

      - name: Crear Tarea en CRM
        run: |
          echo "📌 Creando tarea para lead caliente en CRM..."

      - name: Crear Tarea en CRM
        run: |
          # Crear alerta interna y asignar tarea a responsable
          echo "Creando tarea en CRM para lead caliente"
